Add multitude of features to the toolkit
BHoM/LadybugTools_Toolkit pull request #90
Opened 2023-02-10 12:47 UTC by tg359

### Issues addressed by this PR

Closes #89

@tg359 to add list of new features here

### Test files

### Changelog

### Additional comments

2023-02-14 19:21 UTC, jamesramsden-bh requested changes
Only a partial review done so far - a few comments made.

2023-02-14 19:21 UTC, jamesramsden-bh commented on LadybugTools_Engine/Create/Shelter.cs
> +        [Input("windPorosity", "The porosity of this shelter object to wind.")]
Requires range check between 0 to 1

2023-02-14 19:21 UTC, jamesramsden-bh commented on LadybugTools_Engine/Create/Shelter.cs
> +        [Input("radiationPorosity", "The porosity of this shelter object to radiation.")]
Requires range check between 0 and 1

2023-02-14 19:21 UTC, jamesramsden-bh commented on LadybugTools_Engine/Create/Shelter.cs
> +            return new Shelter() { Vertices = vertices, WindPorosity = windPorosity, RadiationPorosity = radiationPorosity };
There are more BHoM-friendly ways of defining the control points of the shelter - a `List<Point>` - or even saving a Polyline object to the Shelter object would be more appropriate.

2023-02-21 15:45 UTC, jamesramsden-bh commented on LadybugTools_Engine/Create/Shelter.cs
> +            return new Shelter() { Vertices = vertices, WindPorosity = windPorosity, RadiationPorosity = radiationPorosity };
After reviewing this in more detail, the original solution is necessary to allow for the correct serialisation/deserialisation.

2023-02-28 16:38 UTC, jamesramsden-bh commented on LadybugTools_Engine/Create/Shelter.cs
> +        [Input("windPorosity", "The porosity of this shelter object to wind.")]
Resolved via Create.Shelter

2023-02-28 16:39 UTC, jamesramsden-bh commented on LadybugTools_Engine/Create/Shelter.cs
> +        [Input("radiationPorosity", "The porosity of this shelter object to radiation.")]
Resolved via Create.Shelter

2023-02-28 16:39 UTC, jamesramsden-bh commented
@BHoMBot check required

2023-02-28 16:42 UTC, jamesramsden-bh submitted a review, later dismissed
Tested BHoM methods in GH with a range of shelters and typologies, and exploded outputs to ensure all looks sensible. Ran unit tests on Python stuff.

2023-02-28 16:44 UTC, jamesramsden-bh commented
@BHoMBot check code-compliance

2023-03-01 16:47 UTC, jamesramsden-bh commented
@BHoMBot check core

2023-03-01 16:53 UTC, jamesramsden-bh commented
@BHoMBot check core

2023-03-01 16:58 UTC, jamesramsden-bh commented
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check documentation-compliance
@BHoMBot check null-handling
@BHoMBot check project-compliance
@BHoMBot check unit-tests

2023-03-01 17:07 UTC, jamesramsden-bh commented
@BHoMBot check null-handling

2023-03-01 17:15 UTC, jamesramsden-bh commented
@BHoMBot check null-handling

2023-03-02 09:12 UTC, jamesramsden-bh commented
@bhom check null-handling

2023-03-02 15:17 UTC, jamesramsden-bh commented
@BHoMBot check null-handling

2023-03-02 15:39 UTC, jamesramsden-bh commented
@BHoMBot check null-handling

2023-03-03 15:38 UTC, FraserGreenroyd requested changes

2023-03-03 15:38 UTC, FraserGreenroyd commented on LadybugTools_Engine/Query/GetMaterial.cs
> +            if (filter.IsNullOrEmpty())
```suggestion
            if (string.IsNullOrEmpty(filter))
```

2023-03-03 15:38 UTC, FraserGreenroyd commented on LadybugTools_Engine/Query/GetTypology.cs
> +            if (filter.IsNullOrEmpty())
```suggestion
            if (string.IsNullOrEmpty(filter))
```

2023-03-03 15:41 UTC, jamesramsden-bh commented
@BHoMBot check null-handling

2023-03-03 15:59 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2023-03-03 16:09 UTC, FraserGreenroyd requested changes

2023-03-03 16:09 UTC, FraserGreenroyd commented on LadybugTools_Engine/Query/GetMaterial.cs
> +        public static List<ILBTMaterial> GetMaterial(string filter = "")
```suggestion
        [PreviousVersion("6.1", "BH.Engine.LadybugTools.Query.GetMaterial(BH.oM.LadybugTools.Materials)")]
        public static List<ILBTMaterial> GetMaterial(string filter = "")
```

2023-03-03 16:09 UTC, FraserGreenroyd commented on LadybugTools_Engine/Query/GetTypology.cs
> +        public static List<Typology> GetTypology(string filter = "")
```suggestion
        [PreviousVersion("6.1", "BH.Engine.LadybugTools.Query.GetTypology(BH.oM.LadybugTools.Typologies)")]
        public static List<Typology> GetTypology(string filter = "")
```

2023-03-03 16:11 UTC, jamesramsden-bh commented
@BHoMBot check versioning

2023-03-03 17:49 UTC, jamesramsden-bh commented
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check documentation-compliance
@BHoMBot check null-handling
@BHoMBot check project-compliance
@BHoMBot check unit-tests
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check code-compliance

2023-03-03 18:15 UTC, jamesramsden-bh commented
@BHoMBot check serialisation

2023-03-03 18:16 UTC, jamesramsden-bh approved these changes
Approved - null check has been dispensated.

2023-03-03 18:18 UTC, jamesramsden-bh requested changes
Retracting my pass - because the unit tests have failed! And on the same methods that were causing null check trouble. To investigate next week.

2023-03-10 10:10 UTC, jamesramsden-bh commented
Owing to time pressures and fixes required, this PR will be closed for now. This commit will be revisited in the next milestone.

2023-05-22 10:31 UTC, jamesramsden-bh commented
This PR has been re-opened in an attempt to get it merged. Tasks to get it merged:

 - [ ] Get automated tests on Python side passing
 - [ ] Fix any existing BHoM methods that can be easily fixed (usually namespace changes after Python refactoring)
 - [ ] Check and fix any versioning issues

2023-05-22 10:38 UTC, FraserGreenroyd commented
I would also recommend a rebase @jamesramsden-bh @tg359

2023-06-04 00:36 UTC, FraserGreenroyd commented on LadybugTools_Engine/Query/GetMaterial.cs
> +        public static List<ILBTMaterial> GetMaterial(string filter = "")
Needs updating to 6.2 now 😄

2023-06-04 00:36 UTC, FraserGreenroyd commented on LadybugTools_Engine/Query/GetTypology.cs
> +        public static List<Typology> GetTypology(string filter = "")
Same here, update to 6.2

2023-06-04 00:36 UTC, FraserGreenroyd commented on LadybugTools_Engine/Compute/EPWtoCSV.cs
> +        public static string EPWtoCSV(string epwFile, bool includeAdditional = false)
```suggestion
        [PreviousVersion("6.2", "BH.Engine.LadybugTools.Compute.EPWtoCSV(System.String)")]
        public static string EPWtoCSV(string epwFile, bool includeAdditional = false)
```

2023-06-07 09:58 UTC, jamesramsden-bh submitted a review, later dismissed
Reinstalled the venv and ran the test script, all working fine. Have also been working directly with the Python via my own Jupyter scripts without issues. 

Automated tests also fully pass.

2023-06-07 09:59 UTC, jamesramsden-bh commented
@BHoMBot check required

2023-06-07 10:59 UTC, jamesramsden-bh commented
@BHoMBot check project-compliance

2023-06-07 10:59 UTC, jamesramsden-bh commented
@BHoMBot fix project file ref. 14069254324

2023-06-07 11:47 UTC, tg359 commented
@BHoMBot fix project file ref. 14069254324

2023-06-08 10:59 UTC, jamesramsden-bh commented
@BHoMBot check versioning

2023-06-08 13:01 UTC, jamesramsden-bh commented
@BHoMBot check versioning

2023-06-08 13:36 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-06-08 13:56 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-06-08 14:24 UTC, FraserGreenroyd commented
@BHoMBot check versioning

2023-06-08 14:41 UTC, jamesramsden-bh commented
@BHoMBot check versioning

2023-06-08 14:59 UTC, jamesramsden-bh commented
@BHoMBot check versioning

2023-06-08 15:17 UTC, jamesramsden-bh commented
@BHoMBot check unit-tests
@BHoMBot check serialisation
@BHoMBot check project-compliance
@BHoMBot check null-handling
@BHoMBot check documentation-compliance
@BHoMBot check dataset-compliance
@BHoMBot check core
@BHoMBot check copyright-compliance
@BHoMBot check code-compliance

2023-06-08 15:22 UTC, jamesramsden-bh commented
@BHoMBot check installer

2023-06-08 15:24 UTC, FraserGreenroyd approved these changes
I've reviewed the code through with @jamesramsden-bh and am happy my changes have been addressed and this work is working suitably for the work done by @tg359 and @jamesramsden-bh so happy for this to be merged and deployed in 6.2

2023-06-08 15:45 UTC, jamesramsden-bh commented
@BHoMBot check ready-to-merge

2023-06-08 15:50 UTC, merged